# Generated by Django 5.0.1 on 2024-01-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_manufacturer_productimage_category_discription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
